// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBu2Ut_8U5KQOcQiOL44B9jK22s02dxajE',
    appId: '1:386441970583:web:41318c0cdd9748f420bad2',
    messagingSenderId: '386441970583',
    projectId: 'nstrack-ecb44',
    authDomain: 'nstrack-ecb44.firebaseapp.com',
    storageBucket: 'nstrack-ecb44.firebasestorage.app',
    measurementId: 'G-2GC6P5VCYJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcCOGU0927U0TPEOhyccxtoAHTbrVvalg',
    appId: '1:386441970583:android:d912f297372d1d2920bad2',
    messagingSenderId: '386441970583',
    projectId: 'nstrack-ecb44',
    storageBucket: 'nstrack-ecb44.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCs39jhC9JdFrySIm0UPKMSdLGP7jpq2-E',
    appId: '1:386441970583:ios:8239b9d0e3c4400c20bad2',
    messagingSenderId: '386441970583',
    projectId: 'nstrack-ecb44',
    storageBucket: 'nstrack-ecb44.firebasestorage.app',
    iosBundleId: 'com.example.nstrackapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCs39jhC9JdFrySIm0UPKMSdLGP7jpq2-E',
    appId: '1:386441970583:ios:8239b9d0e3c4400c20bad2',
    messagingSenderId: '386441970583',
    projectId: 'nstrack-ecb44',
    storageBucket: 'nstrack-ecb44.firebasestorage.app',
    iosBundleId: 'com.example.nstrackapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBu2Ut_8U5KQOcQiOL44B9jK22s02dxajE',
    appId: '1:386441970583:web:08dcb0f0fbd1eceb20bad2',
    messagingSenderId: '386441970583',
    projectId: 'nstrack-ecb44',
    authDomain: 'nstrack-ecb44.firebaseapp.com',
    storageBucket: 'nstrack-ecb44.firebasestorage.app',
    measurementId: 'G-YQBZLFD4YP',
  );

}